// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IM.Friend.proto

package com.mogujie.tt.protobuf;

public final class IMFriend {
  private IMFriend() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface IMGetUserInfoReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Friend.IMGetUserInfoReq)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string nick_name = 1;</code>
     */
    boolean hasNickName();
    /**
     * <code>required string nick_name = 1;</code>
     */
    java.lang.String getNickName();
    /**
     * <code>required string nick_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNickNameBytes();
  }
  /**
   * Protobuf type {@code IM.Friend.IMGetUserInfoReq}
   */
  public static final class IMGetUserInfoReq extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:IM.Friend.IMGetUserInfoReq)
      IMGetUserInfoReqOrBuilder {
    // Use IMGetUserInfoReq.newBuilder() to construct.
    private IMGetUserInfoReq(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMGetUserInfoReq(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final IMGetUserInfoReq defaultInstance;
    public static IMGetUserInfoReq getDefaultInstance() {
      return defaultInstance;
    }

    public IMGetUserInfoReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private IMGetUserInfoReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              nickName_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<IMGetUserInfoReq> PARSER =
        new com.google.protobuf.AbstractParser<IMGetUserInfoReq>() {
      public IMGetUserInfoReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMGetUserInfoReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IMGetUserInfoReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NICK_NAME_FIELD_NUMBER = 1;
    private java.lang.Object nickName_;
    /**
     * <code>required string nick_name = 1;</code>
     */
    public boolean hasNickName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string nick_name = 1;</code>
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string nick_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      nickName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasNickName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNickNameBytes());
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNickNameBytes());
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code IM.Friend.IMGetUserInfoReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:IM.Friend.IMGetUserInfoReq)
        com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReqOrBuilder {
      // Construct using com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        nickName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq getDefaultInstanceForType() {
        return com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq.getDefaultInstance();
      }

      public com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq build() {
        com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq buildPartial() {
        com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq result = new com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nickName_ = nickName_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq other) {
        if (other == com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq.getDefaultInstance()) return this;
        if (other.hasNickName()) {
          bitField0_ |= 0x00000001;
          nickName_ = other.nickName_;
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNickName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mogujie.tt.protobuf.IMFriend.IMGetUserInfoReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object nickName_ = "";
      /**
       * <code>required string nick_name = 1;</code>
       */
      public boolean hasNickName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string nick_name = 1;</code>
       */
      public java.lang.String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nickName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string nick_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        java.lang.Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string nick_name = 1;</code>
       */
      public Builder setNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nickName_ = value;
        
        return this;
      }
      /**
       * <code>required string nick_name = 1;</code>
       */
      public Builder clearNickName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nickName_ = getDefaultInstance().getNickName();
        
        return this;
      }
      /**
       * <code>required string nick_name = 1;</code>
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nickName_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Friend.IMGetUserInfoReq)
    }

    static {
      defaultInstance = new IMGetUserInfoReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Friend.IMGetUserInfoReq)
  }

  public interface IMMakeFriendReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IM.Friend.IMMakeFriendReq)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint32 user_account = 1;</code>
     */
    boolean hasUserAccount();
    /**
     * <code>required uint32 user_account = 1;</code>
     */
    int getUserAccount();

    /**
     * <code>required string attach_msg = 2;</code>
     */
    boolean hasAttachMsg();
    /**
     * <code>required string attach_msg = 2;</code>
     */
    java.lang.String getAttachMsg();
    /**
     * <code>required string attach_msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getAttachMsgBytes();

    /**
     * <code>required .IM.BaseDefine.FriendPermission friend_permission = 3;</code>
     */
    boolean hasFriendPermission();
    /**
     * <code>required .IM.BaseDefine.FriendPermission friend_permission = 3;</code>
     */
    com.mogujie.tt.protobuf.IMBaseDefine.FriendPermission getFriendPermission();
  }
  /**
   * Protobuf type {@code IM.Friend.IMMakeFriendReq}
   */
  public static final class IMMakeFriendReq extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:IM.Friend.IMMakeFriendReq)
      IMMakeFriendReqOrBuilder {
    // Use IMMakeFriendReq.newBuilder() to construct.
    private IMMakeFriendReq(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IMMakeFriendReq(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final IMMakeFriendReq defaultInstance;
    public static IMMakeFriendReq getDefaultInstance() {
      return defaultInstance;
    }

    public IMMakeFriendReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private IMMakeFriendReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userAccount_ = input.readUInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              attachMsg_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.mogujie.tt.protobuf.IMBaseDefine.FriendPermission value = com.mogujie.tt.protobuf.IMBaseDefine.FriendPermission.valueOf(rawValue);
              if (value == null) {
                unknownFieldsCodedOutput.writeRawVarint32(tag);
                unknownFieldsCodedOutput.writeRawVarint32(rawValue);
              } else {
                bitField0_ |= 0x00000004;
                friendPermission_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<IMMakeFriendReq> PARSER =
        new com.google.protobuf.AbstractParser<IMMakeFriendReq>() {
      public IMMakeFriendReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMMakeFriendReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IMMakeFriendReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USER_ACCOUNT_FIELD_NUMBER = 1;
    private int userAccount_;
    /**
     * <code>required uint32 user_account = 1;</code>
     */
    public boolean hasUserAccount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 user_account = 1;</code>
     */
    public int getUserAccount() {
      return userAccount_;
    }

    public static final int ATTACH_MSG_FIELD_NUMBER = 2;
    private java.lang.Object attachMsg_;
    /**
     * <code>required string attach_msg = 2;</code>
     */
    public boolean hasAttachMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string attach_msg = 2;</code>
     */
    public java.lang.String getAttachMsg() {
      java.lang.Object ref = attachMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          attachMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string attach_msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAttachMsgBytes() {
      java.lang.Object ref = attachMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        attachMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FRIEND_PERMISSION_FIELD_NUMBER = 3;
    private com.mogujie.tt.protobuf.IMBaseDefine.FriendPermission friendPermission_;
    /**
     * <code>required .IM.BaseDefine.FriendPermission friend_permission = 3;</code>
     */
    public boolean hasFriendPermission() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .IM.BaseDefine.FriendPermission friend_permission = 3;</code>
     */
    public com.mogujie.tt.protobuf.IMBaseDefine.FriendPermission getFriendPermission() {
      return friendPermission_;
    }

    private void initFields() {
      userAccount_ = 0;
      attachMsg_ = "";
      friendPermission_ = com.mogujie.tt.protobuf.IMBaseDefine.FriendPermission.Per_ShieldMsg;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUserAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAttachMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFriendPermission()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, userAccount_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAttachMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, friendPermission_.getNumber());
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, userAccount_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAttachMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, friendPermission_.getNumber());
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code IM.Friend.IMMakeFriendReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:IM.Friend.IMMakeFriendReq)
        com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReqOrBuilder {
      // Construct using com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userAccount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        attachMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        friendPermission_ = com.mogujie.tt.protobuf.IMBaseDefine.FriendPermission.Per_ShieldMsg;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq getDefaultInstanceForType() {
        return com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq.getDefaultInstance();
      }

      public com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq build() {
        com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq buildPartial() {
        com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq result = new com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userAccount_ = userAccount_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.attachMsg_ = attachMsg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.friendPermission_ = friendPermission_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq other) {
        if (other == com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq.getDefaultInstance()) return this;
        if (other.hasUserAccount()) {
          setUserAccount(other.getUserAccount());
        }
        if (other.hasAttachMsg()) {
          bitField0_ |= 0x00000002;
          attachMsg_ = other.attachMsg_;
          
        }
        if (other.hasFriendPermission()) {
          setFriendPermission(other.getFriendPermission());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserAccount()) {
          
          return false;
        }
        if (!hasAttachMsg()) {
          
          return false;
        }
        if (!hasFriendPermission()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mogujie.tt.protobuf.IMFriend.IMMakeFriendReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int userAccount_ ;
      /**
       * <code>required uint32 user_account = 1;</code>
       */
      public boolean hasUserAccount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 user_account = 1;</code>
       */
      public int getUserAccount() {
        return userAccount_;
      }
      /**
       * <code>required uint32 user_account = 1;</code>
       */
      public Builder setUserAccount(int value) {
        bitField0_ |= 0x00000001;
        userAccount_ = value;
        
        return this;
      }
      /**
       * <code>required uint32 user_account = 1;</code>
       */
      public Builder clearUserAccount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userAccount_ = 0;
        
        return this;
      }

      private java.lang.Object attachMsg_ = "";
      /**
       * <code>required string attach_msg = 2;</code>
       */
      public boolean hasAttachMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string attach_msg = 2;</code>
       */
      public java.lang.String getAttachMsg() {
        java.lang.Object ref = attachMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            attachMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string attach_msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAttachMsgBytes() {
        java.lang.Object ref = attachMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          attachMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string attach_msg = 2;</code>
       */
      public Builder setAttachMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        attachMsg_ = value;
        
        return this;
      }
      /**
       * <code>required string attach_msg = 2;</code>
       */
      public Builder clearAttachMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        attachMsg_ = getDefaultInstance().getAttachMsg();
        
        return this;
      }
      /**
       * <code>required string attach_msg = 2;</code>
       */
      public Builder setAttachMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        attachMsg_ = value;
        
        return this;
      }

      private com.mogujie.tt.protobuf.IMBaseDefine.FriendPermission friendPermission_ = com.mogujie.tt.protobuf.IMBaseDefine.FriendPermission.Per_ShieldMsg;
      /**
       * <code>required .IM.BaseDefine.FriendPermission friend_permission = 3;</code>
       */
      public boolean hasFriendPermission() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .IM.BaseDefine.FriendPermission friend_permission = 3;</code>
       */
      public com.mogujie.tt.protobuf.IMBaseDefine.FriendPermission getFriendPermission() {
        return friendPermission_;
      }
      /**
       * <code>required .IM.BaseDefine.FriendPermission friend_permission = 3;</code>
       */
      public Builder setFriendPermission(com.mogujie.tt.protobuf.IMBaseDefine.FriendPermission value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        friendPermission_ = value;
        
        return this;
      }
      /**
       * <code>required .IM.BaseDefine.FriendPermission friend_permission = 3;</code>
       */
      public Builder clearFriendPermission() {
        bitField0_ = (bitField0_ & ~0x00000004);
        friendPermission_ = com.mogujie.tt.protobuf.IMBaseDefine.FriendPermission.Per_ShieldMsg;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IM.Friend.IMMakeFriendReq)
    }

    static {
      defaultInstance = new IMMakeFriendReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IM.Friend.IMMakeFriendReq)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
